name: Volte CI

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.201'
    - name: Compile
      run: bash build.sh
    - name: Upload Linux binary
      uses: actions/upload-artifact@main
      with:
        name: Volte Linux
        path: src/bin/Release/netcoreapp3.1/linux-x64/publish/Volte
    - name: Upload Windows binary
      uses: actions/upload-artifact@main
      with:
        name: Volte Windows
        path: src/bin/Release/netcoreapp3.1/win10-x64/publish/Volte.exe